allowBuilds:
  '@tsparticles/engine': true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - "@tsparticles/engine"
  - react-tsparticles
  - sharp
  - tsparticles-engine
  - unrs-resolver
