/**
 * media.config.ts
 * ---------------
 * Auto-generated by scripts/upload-to-blob.mjs
 * DO NOT edit manually — run `pnpm blob:upload` to regenerate.
 *
 * All URLs point to Vercel Blob CDN (global edge, zero egress cost on Vercel).
 *
 * ⚠️  This file contains placeholder URLs.
 *     Run `pnpm blob:upload` to upload your images and populate real CDN URLs.
 */

// ── Static assets ─────────────────────────────────────────────────────────────
export const media = {
  /** Hero section avatar photo */
  avatar: "/Avatar.webp",

  /** Navbar logo */
  logo: "/logo.webp",

  /** Open Graph / Twitter card image (1200×630) */
  ogImage: "https://wahb.space/og-image.webp",

  /** Apple Touch Icon (180×180) */
  appleTouchIcon: "/apple-touch-icon.webp",

  /** PWA manifest icon 192×192 */
  webManifest192: "/web-app-manifest-192x192.webp",

  /** PWA manifest icon 512×512 */
  webManifest512: "/web-app-manifest-512x512.webp",

  /** Favicon 96×96 */
  favicon96: "/favicon-96x96.webp",
} as const;

export type MediaKey = keyof typeof media;

// ── Project screenshot galleries ──────────────────────────────────────────────
// Keyed by project id (matches app/data/projects.json → id field).
// These are read by project card / case study components.
// ⚠️  Run `pnpm blob:upload` to replace these with Vercel Blob CDN URLs.
export const projectMedia: Record<string, string[]> = {
  /** ClearPath — AI Document Intelligence Platform */
  "clearpath": [
    "/Project/ClearPath/landing.webp",
    "/Project/ClearPath/dashboard.webp",
    "/Project/ClearPath/results.webp",
  ],

  /** EconoQuest — AI Economics Simulator */
  "econoquest": [
    "/Project/EconoQuest/landing.webp",
    "/Project/EconoQuest/nation-selection.webp",
    "/Project/EconoQuest/playground.jpg",
    "/Project/EconoQuest/report.jpg",
    "/Project/EconoQuest/hall-of-fame.jpg",
  ],

  /** EcoLens — AI Waste Classifier */
  "ecolens": [
    "/Project/EcoLens/dashboard.webp",
    "/Project/EcoLens/leaderboard.jpg",
    "/Project/EcoLens/achivements.webp",
  ],

  /** Client & Developer Collaboration Platform */
  "client-dev-platform": [
    "/Project/Platform/home.webp",
    "/Project/Platform/Dashboard.webp",
    "/Project/Platform/projects.webp",
    "/Project/Platform/Quote.webp",
  ],

  /** Modern Online Store */
  "ecom-1": [
    "/Project/Ecom/light-shop.webp",
    "/Project/Ecom/light-men.webp",
    "/Project/Ecom/light-women.webp",
    "/Project/Ecom/light-product.webp",
    "/Project/Ecom/stripe.webp",
  ],
};
