import { Metadata } from "next";

export const siteMetadata: Metadata = {
  title: "Wahb Amir | Full-Stack Engineer & AI Developer",
  description:
    "Wahb Amir (Wahb) is a full-stack engineer and AI developer building high-performance web applications, RAG pipelines, and production-ready systems — Creator of ClearPath (USAII 2026) · Technical Award at Hackonomics 2026 · 3rd Place at Hack for Humanity 2026.",
  metadataBase: new URL("https://wahb.space"),
  keywords: [
    "Wahb Amir",
    "Wahb",
    "full-stack engineer",
    "software engineer",
    "AI developer",
    "AI engineer",
    "RAG pipeline",
    "Document Intelligence",
    "LangChain",
    "Next.js",
    "React",
    "Node.js",
    "Serverless",
    "Fastify",
    "TypeScript",
    "Supabase",
    "pgvector",
    "Groq",
    "Llama 3",
    "WebSocket",
    "Tailwind CSS",
    "web performance",
    "machine learning",
    "ClearPath AI",
    "EconoQuest",
    "EcoLens",
    "USAII 2026",
    "Hackonomics 2026",
    "Hack for Humanity 2026",
    "portfolio",
  ],
  authors: [{ name: "Wahb Amir", url: "https://wahb.space" }],
  creator: "Wahb Amir",
  applicationName: "Wahb Amir Portfolio",
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: "https://wahb.space/",
    languages: {
      "en-US": "https://wahb.space/",
      en: "https://wahb.space/",
    },
  },
  openGraph: {
    title: "Wahb Amir | Full-Stack Engineer & AI Developer",
    description:
      "Portfolio of Wahb Amir — Creator of ClearPath (USAII 2026) · Technical Award at Hackonomics 2026 · 3rd Place at Hack for Humanity 2026. Building high-performance web apps, RAG pipelines, and scalable systems from idea to production.",
    url: "https://wahb.space",
    siteName: "Wahb Amir Portfolio",
    images: [
      {
        url: "https://wahb.space/og-image.webp",
        width: 1200,
        height: 630,
        alt: "Wahb Amir — Full-Stack Engineer & AI Developer",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    site: "@wahbdev",
    creator: "@wahbdev",
    title: "Wahb Amir | Full-Stack Engineer & AI Developer",
    description:
      "USAII 2026 · Technical Award — Hackonomics 2026 · 3rd Place — Hack for Humanity 2026. Building high-performance web apps and practical AI tools.",
    images: ["https://wahb.space/og-image.webp"],
  },
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon-16x16.webp",
    apple: "/apple-touch-icon.webp",
  },
  manifest: "/site.webmanifest",
};
