"use client"
import "./globals.css";
import "./tailwind-out.css";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import "./tailwind-out.css";
import { AnimatePresence, motion } from "framer-motion";
import { usePathname } from "next/navigation";
import PageTransition from "./Component/PageTransition"; // Adjust the path if needed

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export default function RootLayout({ children }) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AnimatePresence mode="wait" initial={false}>
          <PageTransition key={pathname}>{children}</PageTransition>
        </AnimatePresence>
      </body>
    </html>
  );
}
